#!/bin/sh
#
#  bspwmrc
#


# desktops
bspc monitor -d             1 2 3 4 5 6
#bspc config top_padding              26
bspc config border_radius 10

_() { bspc config "$@"; }

# mouse
xsetroot -cursor_name       left_ptr
_ pointer_modifier          mod4
_ pointer_motion_interval   10

_ focus_follows_pointer     true
_ pointer_follows_focus     false


# borders/gaps
_ window_gap                40
_ gapless_monocle           false

_ border_width              0
_ borderless_monocle        true
_ normal_border_color       "#19191C"
_ focused_border_color      "#202026"


# other
_ single_monocle            true


#
#   rules
#
bspc rule -a feh            state=floating
bspc rule -a tabbed         state=floating
bspc rule -a Gcolor3        state=floating
bspc rule -a kitty          state=floating
bspc rule -a discord        desktop="2" state=pseudo_tiled follow=off
bspc rule -a firefox        desktop="1" follow=off


#
#   autostart
#
borders &
pkill picom
pkill dunst
pkill sxhkd

sleep 0.1

picom &
dunst &
sxhkd &
sxhkd -c ${XDG_CONFIG_HOME:-~/.config}/sxhkd/bspwm &
mpd
wal -R
nvidia-settings -l
$TERMINAL picom --config /home/lxvi/.config/picom/picom.conf 

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
